apiVersion: v1
kind: Pod
metadata:
  name: ddtest
spec:
  containers:
  - image: quay.io/cresta/test-dd:latest
    name: ddserver
    env:
      - name: DATADOG_SERVICE_NAME
        value: ddserver
      - name: ENV
        value: dev
    volumeMounts:
    - name: dsdsocket
      mountPath: /var/run/datadog
      readOnly: true
  - image: quay.io/cresta/test-dd:latest
    name: ddclient
    env:
      - name: ENV
        value: dev
    volumeMounts:
    - name: dsdsocket
      mountPath: /var/run/datadog
      readOnly: true
  volumes:
  - hostPath:
      path: /var/run/datadog/
    name: dsdsocket
