apiVersion: v1
kind: Pod
metadata:
  name: ddtest
spec:
  containers:
  - image: quay.io/cresta/test-dd:v0.1.6
    name: ddtest
    volumeMounts:
    - name: dsdsocket
      mountPath: /var/run/datadog
      readOnly: true
  volumes:
  - hostPath:
      path: /var/run/datadog/
    name: dsdsocket
